config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "accounts#index"

  resources :accounts do
    member do
      get :vat_search
    end
  end
end

app/models/account.rb
class Account < ApplicationRecord
  validates :name, presence: true
  validates :city, presence: true
  validates :zipcode, presence: true
  validates :address, presence: true
  validates :vat, presence: true, uniqueness: true

  def self.valvat(vat)
    Valvat.new("EL"+vat.to_s).exists?(detail: true)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  before_action :load_account_instance, only: [:show, :edit, :update, :destroy]
  def index
  end

  def show
  end

  def edit
  end

  def update

    if @account.update(permitted_params)
      respond_to do |format|
        format.turbo_stream { flash.now[:notice] = 'Account updated succesfully.'}
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(permitted_params)
    if @account.save
      respond_to do |format|
        format.html { redirect_to root_path, notice: 'Account created succesfully.' }
        format.turbo_stream { flash.now[:notice] = 'Account created succesfully.'}
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    respond_to do |format|
      if @account.destroy
        format.turbo_stream do
          flash.now[:notice] = 'Account has been deleted succesfully'
        end
      else
        format.turbo_stream { flash.now[:alert] = 'Account is not deleted' }
      end
    end
  end

  def vat_search
    vat = Account.valvat(params[:id])

    if vat
      @name = vat[:name].split('||').first
      @area = vat[:address].split('-').last

      address_with_zip = vat[:address].split('-').first
      @zipcode = address_with_zip.split.last

      address_array = address_with_zip.split
      address_array.pop
      @address = address_array.join(' ')
    end


    respond_to do |format|
      if vat
        format.turbo_stream { flash.now[:notice] = 'VAT was succesfully retrieved.'}
      else
        format.turbo_stream { flash.now[:alert] = 'VAT is not valid.'}
      end
    end

  end

  private
  def permitted_params
    params.require(:account).permit(:vat, :name, :city, :zipcode, :address)
  end

  def load_account_instance
    @account = Account.where(id: params[:id])[0]
    if @account.nil?
      redirect_to root_path, alert: 'This account doesn\'t exist.'
    else
      @account
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def turbo_stream_flash_message
    turbo_stream.prepend 'flash', partial: 'layouts/notifications'
  end

end

app/views/accounts/_form.html.erb
<%= form_with model: obj, class:'container-flex', data: { controller: 'vat-search' } do |f| %>
  <div class="row g-3 my-3 align-items-center">
    <div class="col-3 form-floating">
      <%= f.text_field :vat, class: 'form-control', placeholder: 'VAT Number', data: {vat_search_target: 'vatField', action: 'keyup->vat-search#count' } %>
      <%= f.label :vat, 'GR VAT Number (9 digits)' %>
      <small class="text-muted" data-vat-search-target="textMuted"></small>
    </div>
    <div class="col">
      <%= link_to 'Auto-fill', '#', class: 'btn btn-secondary', data: {vat_search_target: 'queryBtn', action: 'vat-search#query'} %>
    </div>
  </div>
  <%= turbo_frame_tag 'account_form_fields' do %>
    <div class="row g-3 my-3">
      <div class="col-8 form-floating">
        <%= f.text_field :name, class: 'form-control', placeholder: 'Name', hint: false %>
        <%= f.label :name, 'Name' %>
      </div>
      <div class="col-4 form-floating">
        <%= f.text_field :zipcode, class: 'form-control', placeholder: 'Zipcode' %>
        <%= f.label :zipcode, 'Zipcode' %>
      </div>
    </div>
    <div class="row g-3 my-3">
      <div class="col-8 form-floating">
        <%= f.text_field :address, class: 'form-control', placeholder: 'Address' %>
        <%= f.label :address, 'Address' %>
      </div>
      <div class="col-4 form-floating">
        <%= f.text_field :city, class: 'form-control', placeholder: 'City / Area' %>
        <%= f.label :city, 'City / Area' %>
      </div>
    </div>
    <div class="row my-3">
      <div class="col">
        <%= f.submit class: 'btn btn-primary' %>
        <%= link_to 'Index', root_path, class: 'btn btn-secondary' %>
      </div>
    </div>
  <% end %>
<% end %>
<% if !@account.new_record? %>
  <div class="row">
    <hr class="hr" />
    <div class="col-auto">
      <%= button_to 'Delete Account', account_path(@account), method: :delete, data: { turbo_confirm: 'Are you sure;' }, class: 'btn btn-danger' %>
    </div>
  </div>
<% end %>

app/views/accounts/_form_notifications.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">There were some issues</h4>
    <p>Please check the form for the following issues</p>
    <hr>
    <% obj.errors.full_messages.each_with_index do |msg, index| %>
      <p class="mb-0"><%= "#{index + 1}. #{msg}" %></p>
    <% end %>
  </div>
<% end %>

app/views/accounts/create.turbo_stream.erb
<%= turbo_stream_flash_message %>

<% if @account.errors.empty? %>
  <%= turbo_stream.update 'main_container' do %>
    <div class="row g-3">
      <div class="col-12">
        <h1>Account has been created.</h1>
      </div>
      <div class="col-12">
        <%= link_to 'Return to Index', accounts_path, class: 'btn btn-primary' %>
        <%= link_to 'Edit Account', edit_account_path(@account), class: 'btn btn-warning' %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/accounts/destroy.turbo_stream.erb
<%= turbo_stream_flash_message %>


  <%= turbo_stream.update 'main_container' do %>
    <div class="row g-3">
      <div class="col-12">
        <% if @account.errors.any? %>
          <h1>Account is not deleted.</h1>
        <% else %>
          <h1>Account deleted succesfully.</h1>
        <% end %>
      </div>
      <div class="col-12">
        <%= link_to 'Return to Index', accounts_path, class: 'btn btn-primary' %>
        <%= link_to 'Edit Account', edit_account_path(@account), class: 'btn btn-warning' %>
      </div>
    </div>
  <% end %>

app/views/accounts/edit.html.erb
<%= turbo_frame_tag 'main_container' do %>
  <div class="row g-3">
    <div class="col-12">
      <h1>Edit Account with VAT: <%= @account.vat %></h1>
    </div>
    <div class="col-12">
      <%= render 'form_notifications', obj: @account %>
    </div>

    <div class="col-12">
      <%= render 'form', obj: @account %>
    </div>
  </div>
<% end %>

app/views/accounts/index.html.erb
<%= turbo_frame_tag 'main_container' do %>
  <div class="row g-3">
    <div class="col-12">
      <h1>List of all Accounts</h1>
    </div>
    <div class="col-12">
      <% if Account.any? %>
        <table class="table table-striped table-hover">
          <thead>
            <tr class="table-primary">
              <th scope="col">VAT</th>
              <th scope="col">Name</th>
              <th scope="col">Address</th>
              <th scope="col">City / Area</th>
              <th scope="col">ZIP Code</th>
              <th scope="col">Delete</th>

            </tr>
          </thead>
          <tbody>
            <% Account.all.each do |account| %>
            <tr>
              <th scope="row">
                <%= link_to edit_account_path(account), class: 'text-decoration-none' do %>
                  <i class="fa-solid fa-pen-to-square"></i>
                  <%= account.vat %>
                <% end %>
              </th>
              <td>
                <%= link_to account_path(account), class: 'text-decoration-none' do %>
                  <i class="fa-solid fa-eye"></i>
                  <%= account.name %>
                <% end %>
              </td>
              <td><%= account.address %></td>
              <td><%= account.city %></td>
              <td><%= account.zipcode %></td>
              <td>
                <%= button_to account_path(account), method: :delete, data: { turbo_confirm: 'Are you sure;' }, class: 'delete-btn' do %>
                  <i class="fa-solid fa-circle-xmark"></i>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
      <p><%= link_to 'Create an account', new_account_path, class: 'btn btn-success' %></p>
      <% end %>
    </div>
  </div>
<% end %>

app/views/accounts/new.html.erb
<%= turbo_frame_tag 'main_container' do %>
  <div class="row g-3">
    <div class="col-12">
      <h1>New Account Form</h1>
    </div>
    <div class="col-12">
      <%= render 'form_notifications', obj: @account %>
    </div>

    <div class="col-12">
      <%= render 'form', obj: @account %>
    </div>
  </div>
<% end %>

app/views/accounts/show.html.erb
<%= turbo_frame_tag 'main_container' do %>
  <div class="row g-3">
    <div class="col-12">
      <h1>Account with VAT: <%= @account.vat %></h1>
    </div>
    <div class="col-12">
      <div class="row g-3 my-3">
        <div class="col-8 form-floating">
          <%= text_field :account, :name, class: 'form-control', placeholder: 'Name', value: @account.name, disabled: true %>
          <%= label :account, :name, 'Name' %>
        </div>
        <div class="col-4 form-floating">
          <%= text_field :account, :zipcode, class: 'form-control', placeholder: 'Zipcode', value: @account.zipcode, disabled: true %>
          <%= label :account, :zipcode, 'Zipcode' %>
        </div>
      </div>
      <div class="row g-3 my-3">
        <div class="col-8 form-floating">
          <%= text_field :account, :address, class: 'form-control', placeholder: 'Address', value: @account.address, disabled: true %>
          <%= label :account, :address, 'Address' %>
        </div>
        <div class="col-4 form-floating">
          <%= text_field :account, :city, class: 'form-control', placeholder: 'City / Area', value: @account.city, disabled: true %>
          <%= label :account, :city, 'City / Area' %>
        </div>
      </div>
    </div>
    <div class="col-12">
      <div class="row g-3">
        <div class="col">
          <%= link_to 'Edit Account', edit_account_path(@account), class: 'btn btn-success' %>
          <%= link_to 'Index', root_path, class: 'btn btn-secondary' %>
        </div>
        <hr class="hr" />
        <div class="col">
          <%= button_to 'Delete Account', account_path(@account), method: :delete, data: { turbo_confirm: 'Are you sure;' }, class: 'btn btn-danger' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/accounts/update.turbo_stream.erb
<%= turbo_stream_flash_message %>

app/views/accounts/vat_search.turbo_stream.erb
<%= turbo_stream_flash_message %>

<%= turbo_stream.replace 'account_name' do %>
  <%= text_field :account, :name, class: 'form-control', placeholder: 'Name', value: @name %>
<% end %>

<%= turbo_stream.replace 'account_address' do %>
  <%= text_field :account, :address, class: 'form-control', placeholder: 'Address', value: @address %>
<% end %>

<%= turbo_stream.replace 'account_city' do %>
  <%= text_field :account, :city, class: 'form-control', placeholder: 'City / Area', value: @area %>
<% end %>

<%= turbo_stream.replace 'account_zipcode' do %>
  <%= text_field :account, :zipcode, class: 'form-control', placeholder: 'Zipcode', value: @zipcode %>
<% end %>

app/views/layouts/_main_nav.html.erb
<nav class="navbar navbar-expand-lg bg-light container">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Wrapp.ai Demo</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Accounts', accounts_path, class: 'nav-link active', 'aria-current': 'page', data: { turbo_frame: 'main_container'} %>
        </li>
        <li class="nav-item">
          <%= link_to 'New Account', new_account_path, class: 'nav-link', data: { turbo_frame: 'main_container'} %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_notifications.html.erb
<% flash.each do |type, msg| %>
  <% if type == 'notice' %>
    <div class="alert alert-success" role="alert" data-action = "click->notifications#dismiss">
      <%= msg %>
    </div>
  <% end %>
  <% if type == 'alert' %>
    <div class="alert alert-danger" role="alert" data-action = "click->notifications#dismiss">
      <%= msg %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wrapp Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container-fluid">

      <div class="row g-5">

        <div class="col-12 bg-light">
          <%= render 'layouts/main_nav' %>
        </div>

        <div class="col-12">
          <div class="container">

            <div class="col-12" id="flash" data-controller="notifications" >
              <%= render 'layouts/notifications' %>
            </div>

            <%= yield %>

          </div>
        </div>

      </div>

    </div>

  </body>

</html>